# Generated by Django 5.0 on 2023-12-18 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snacks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snack",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="snack",
            name="date_time",
        ),
    ]
